const text = [
  `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
  `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
  `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
  `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
  `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
  `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
  "I'm baby pabst venmo prism bitters cornhole gochujang. Hella disrupt unicorn vibecession celiac VHS, ugh cronut paleo distillery ethical snackwave. Squid flexitarian gluten-free occupy fanny pack vinyl readymade letterpress subway tile. Hashtag cardigan tumeric, kombucha try-hard squid raclette pabst PBR&B bruh XOXO whatever put a bird on it occupy godard. Tacos four dollar toast freegan, meggings offal you probably haven't heard of them subway tile blog. Organic paleo same chambray lumbersexual subway tile affogato waistcoat butcher. Health goth kinfolk whatever pok pok.",

  "Chicharrones meggings unicorn blue bottle poke bodega boys hashtag snackwave. Church-key authentic live-edge hashtag, woke +1 cornhole flexitarian lyft vegan sriracha pickled. Kogi 90's cronut, post-ironic bicycle rights edison bulb ennui literally. Mukbang artisan gatekeep pug. Franzen chartreuse snackwave tousled, migas gluten-free palo santo.",

  "Quinoa 8-bit raclette readymade ethical semiotics migas waistcoat, salvia pok pok. Literally pop-up hella put a bird on it fingerstache JOMO waistcoat Brooklyn kombucha banh mi kale chips. Sus fixie enamel pin franzen schlitz bespoke raw denim. Messenger bag plaid meggings occupy. Pop-up celiac Brooklyn, farm-to-table ugh bespoke fingerstache typewriter PBR&B. Direct trade green juice try-hard next level food truck taxidermy put a bird on it, hell of snackwave echo park DIY XOXO keytar",

  "Yr master cleanse kombucha portland forage migas. Literally poutine DIY, selvage plaid succulents flannel. Pour-over dreamcatcher forage quinoa, street art neutra prism sus vape vexillologist banh mi. Kinfolk heirloom retro plaid seitan kickstarter, chia skateboard selfies semiotics snackwave activated charcoal franzen vice cold-pressed. You probably haven't heard of them irony fit bruh affogato palo santo live-edge mixtape mlkshk hammock. Actually tbh ascot bitters. Pok pok sus selfies distillery, shoreditch bicycle rights tumeric godard 90's yuccie skateboard jean shorts swag hot chicken DSA",

  "Shoreditch blue bottle taxidermy humblebrag wayfarers tumeric mlkshk affogato, artisan listicle. Pork belly mixtape sus, pickled lumbersexual vexillologist small batch vegan twee quinoa same butcher seitan. Skateboard knausgaard +1, sriracha bitters PBR&B letterpress shabby chic. Drinking vinegar +1 Brooklyn stumptown raclette ramps DIY cliche chillwave skateboard actually DSA vice 3 wolf moon edison bulb. Hot chicken vexillologist readymade selvage whatever tonx church-key. Tacos distillery chillwave live-edge bodega boys selfies quinoa, street art master cleanse scenester truffaut migas occupy succulents crucifix",

  "Shoreditch intelligentsia photo booth vice disrupt. Ennui organic tattooed celiac viral blue bottle. Unicorn try-hard trust fund, sustainable edison bulb mlkshk iPhone four dollar toast plaid. Retro hexagon mlkshk iPhone tbh. Taxidermy freegan dreamcatcher, 8-bit palo santo cardigan tousled health goth pickled iPhone try-hard enamel pin. Fashion axe tacos taiyaki, echo park 3 wolf moon locavore health goth iceland next level salvia put a bird on it mustache af.",

  "Tilde craft beer DIY single-origin coffee fit, echo park godard tousled gentrify. Jean shorts gluten-free sustainable four loko health goth same. Organic flexitarian gluten-free pinterest iceland, art party DIY semiotics etsy air plant. Tofu vexillologist shabby chic bodega boys, semiotics normcore art party tonx. Man braid celiac fashion axe jean shorts master cleanse succulents. Lomo air plant street art art party copper mug la croix. Twee messenger bag asymmetrical schlitz waistcoat occupy.",

  "Roof party humblebrag try-hard, street art keffiyeh put a bird on it sriracha food truck occupy. Fanny pack farm-to-table photo booth venmo craft beer chicharrones banjo. Gatekeep XOXO activated charcoal salvia keffiyeh praxis small batch. Tofu fixie mumblecore scenester viral pour-over cray hashtag pabst 3 wolf moon.",

  "Roof party humblebrag try-hard, street art keffiyeh put a bird on it sriracha food truck occupy. Fanny pack farm-to-table photo booth venmo craft beer chicharrones banjo. Gatekeep XOXO activated charcoal salvia keffiyeh praxis small batch. Tofu fixie mumblecore scenester viral pour-over cray hashtag pabst 3 wolf moon and the sun is beautiful to look at in the evening because you dont get your eyes burnt. I LOVE YOU!.",

  "Meditation microdosing kogi, disrupt hammock trust fund gatekeep 3 wolf moon. Small batch ramps iceland +1 skateboard edison bulb distillery farm-to-table. Readymade tofu 8-bit, truffaut same forage chia PBR&B fanny pack. Keffiyeh tattooed banjo raclette, pug ethical four loko 8-bit hexagon chillwave mukbang helvetica post-ironic.",

  "Shoreditch lumbersexual same, adaptogen actually crucifix fixie poke polaroid swag. Copper mug bitters seitan salvia shaman, knausgaard vinyl wayfarers brunch. Meggings before they sold out helvetica, fanny pack chillwave pug try-hard. Actually marfa ennui bicycle rights stumptown viral asymmetrical, gatekeep sus schlitz mukbang thundercats helvetica. Poutine aesthetic sartorial mukbang wolf crucifix irony kale chips schlitz retro celiac.",
];
export default text;
